# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperatura')),
                ('pressure', models.FloatField(verbose_name='Pressao')),
                ('density', models.FloatField(verbose_name='Densidade')),
                ('cp', models.FloatField(verbose_name='CP')),
                ('viscosity', models.FloatField(verbose_name='Viscosidade')),
                ('k', models.FloatField(verbose_name='k')),
            ],
            options={
                'verbose_name': 'Agua',
                'verbose_name_plural': 'Aguas',
            },
        ),
        migrations.CreateModel(
            name='Butano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperatura')),
                ('pressure', models.FloatField(verbose_name='Pressao')),
                ('density', models.FloatField(verbose_name='Densidade')),
                ('cp', models.FloatField(verbose_name='CP')),
                ('viscosity', models.FloatField(verbose_name='Viscosidade')),
                ('k', models.FloatField(verbose_name='k')),
            ],
        ),
        migrations.CreateModel(
            name='CO2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperatura')),
                ('pressure', models.FloatField(verbose_name='Pressao')),
                ('density', models.FloatField(verbose_name='Densidade')),
                ('cp', models.FloatField(verbose_name='CP')),
                ('viscosity', models.FloatField(verbose_name='Viscosidade')),
                ('k', models.FloatField(verbose_name='k')),
            ],
        ),
        migrations.CreateModel(
            name='Metano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperatura')),
                ('pressure', models.FloatField(verbose_name='Pressao')),
                ('density', models.FloatField(verbose_name='Densidade')),
                ('cp', models.FloatField(verbose_name='CP')),
                ('viscosity', models.FloatField(verbose_name='Viscosidade')),
                ('k', models.FloatField(verbose_name='k')),
            ],
        ),
        migrations.CreateModel(
            name='Pentano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperatura')),
                ('pressure', models.FloatField(verbose_name='Pressao')),
                ('density', models.FloatField(verbose_name='Densidade')),
                ('cp', models.FloatField(verbose_name='CP')),
                ('viscosity', models.FloatField(verbose_name='Viscosidade')),
                ('k', models.FloatField(verbose_name='k')),
            ],
        ),
        migrations.CreateModel(
            name='RC318',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperatura')),
                ('pressure', models.FloatField(verbose_name='Pressao')),
                ('density', models.FloatField(verbose_name='Densidade')),
                ('cp', models.FloatField(verbose_name='CP')),
                ('viscosity', models.FloatField(verbose_name='Viscosidade')),
                ('k', models.FloatField(verbose_name='k')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.FloatField()),
            ],
        ),
    ]
