# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cascoetubos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='Agua',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Butano',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='CO2',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Metano',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Pentano',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='RC318',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
