# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cascoetubos', '0002_auto_20170331_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='result_casc_tb',
        ),
        migrations.AddField(
            model_name='resultado',
            name='result_fl',
            field=models.CharField(default='null', max_length=7000, verbose_name='Resultado FluidoDinamico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='result_geral',
            field=models.CharField(default='null', max_length=7000, verbose_name='Resultado de Analise Geral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='result_pres',
            field=models.CharField(default='null', max_length=7000, verbose_name='Resultado Queda de Pressa'),
            preserve_default=False,
        ),
    ]
