# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duplotubo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agua',
            old_name='viscosity',
            new_name='Viscos',
        ),
        migrations.RenameField(
            model_name='agua',
            old_name='density',
            new_name='densidade',
        ),
        migrations.RenameField(
            model_name='agua',
            old_name='pressure',
            new_name='press',
        ),
        migrations.RenameField(
            model_name='agua',
            old_name='temperature',
            new_name='temp',
        ),
        migrations.RemoveField(
            model_name='agua',
            name='kt',
        ),
    ]
