# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fluido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name=b'Temperatura')),
                ('pressure', models.FloatField(verbose_name=b'Pressao')),
                ('Densidade', models.FloatField(verbose_name=b'Densidade')),
                ('cp', models.FloatField(blank=True, verbose_name=b'CP')),
                ('Viscos', models.FloatField(verbose_name=b'Viscosidade')),
                ('k', models.FloatField(blank=True, verbose_name=b'k')),
            ],
        ),
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('fluido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Fluido')),
            ],
            options={
                'verbose_name': 'Agua',
            },
            bases=('core.fluido',),
        ),
        migrations.CreateModel(
            name='Butano',
            fields=[
                ('fluido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Fluido')),
            ],
            options={
                'verbose_name': 'Butano',
            },
            bases=('core.fluido',),
        ),
        migrations.CreateModel(
            name='CO2',
            fields=[
                ('fluido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Fluido')),
            ],
            options={
                'verbose_name': 'CO2',
            },
            bases=('core.fluido',),
        ),
        migrations.CreateModel(
            name='Metano',
            fields=[
                ('fluido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Fluido')),
            ],
            options={
                'verbose_name': 'Metano',
            },
            bases=('core.fluido',),
        ),
        migrations.CreateModel(
            name='Pentano',
            fields=[
                ('fluido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Fluido')),
            ],
            options={
                'verbose_name': 'Pentano',
            },
            bases=('core.fluido',),
        ),
        migrations.CreateModel(
            name='RC318',
            fields=[
                ('fluido_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Fluido')),
            ],
            options={
                'verbose_name': 'RC318',
            },
            bases=('core.fluido',),
        ),
    ]
